[package]
name = "time-parse"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
failure = "0.1"
nom = "4.0.0-beta3"

[dev-dependencies]
bencher = "0.1"

[[bench]]
name = "duration_bench"
harness = false

[profile.bench]
lto = true
